export const TOPO_SMT_STYLES = [
  {
    selector: 'node',
    style: {
      shape: 'round-rectangle',
      width: 160,
      height: 64,
      'background-color': '#2d2d2d',
      'border-width': 2,
      'border-color': '#666',
      label: 'data(label)',
      color: '#e6e6e6',
      'font-size': 11,
      'font-family': 'Consolas, Monaco, "Courier New", monospace',
      'text-wrap': 'wrap',
      'text-max-width': 140,
      'text-halign': 'center',
      'text-valign': 'center',
    },
  },
  { selector: 'node[status = "equal"]', style: { 'border-color': '#4caf50' } },
  { selector: 'node[status = "fail"]', style: { 'border-color': '#ff5252' } },
  { selector: 'node[status = "unmatched"]', style: { 'border-color': '#ff9800' } },
  {
    selector: 'node:selected',
    style: {
      'overlay-color': '#007acc',
      'overlay-opacity': 0.12,
    },
  },
  {
    selector: 'edge',
    style: {
      width: 1.5,
      'line-color': '#666',
      'target-arrow-color': '#666',
      'target-arrow-shape': 'triangle',
      'curve-style': 'taxi',
      'taxi-direction': 'vertical',
      'taxi-turn-min-distance': 8,
    },
  },
]

export const KIR_GRAPH_STYLES = [
  { selector: 'node', style: { 'background-color': '#888', label: 'data(label)', color: '#e6e6e6', 'font-size': 10, 'text-wrap': 'wrap' } },
  {
    selector: 'edge',
    style: {
      width: 2,
      'line-color': '#777',
      'target-arrow-color': '#777',
      'target-arrow-shape': 'triangle',
      'curve-style': 'bezier',
      'text-rotation': 'autorotate',
      'font-size': 9,
      color: '#e6e6e6',
      'text-background-opacity': 0.8,
      'text-background-color': '#111',
    },
  },
  { selector: 'edge[kind = "Call"]', style: { 'line-color': '#9e9e9e', 'target-arrow-color': '#9e9e9e' } },
  { selector: 'edge[kind = "Input"]', style: { 'line-color': '#4caf50', 'target-arrow-color': '#4caf50' } },
  { selector: 'edge[kind = "Return"]', style: { 'line-color': '#ff9800', 'target-arrow-color': '#ff9800' } },
  { selector: 'edge[kind = "Anchor"]', style: { 'line-color': '#607d8b', 'target-arrow-color': '#607d8b' } },
  { selector: 'edge[kind = "Field"]', style: { 'line-color': '#00bcd4', 'target-arrow-color': '#00bcd4' } },
  { selector: 'edge[kind = "Type"]', style: { 'line-color': '#8bc34a', 'target-arrow-color': '#8bc34a' } },
  { selector: 'node[kind = "Function"]', style: { 'background-color': '#1976d2' } },
  { selector: 'node[kind = "Param"]', style: { 'background-color': '#546e7a' } },
  { selector: 'node[kind = "UnitType"]', style: { 'background-color': '#37474f' } },
  { selector: 'node[kind = "Struct"]', style: { 'background-color': '#00897b' } },
  { selector: 'node[kind = "FuncName"]', style: { 'background-color': '#ab47bc' } },
  { selector: 'node[kind = "VarName"]', style: { 'background-color': '#e91e63' } },
  { selector: 'edge[mismatch]', style: { 'line-color': '#ff5252', 'target-arrow-color': '#ff5252', 'target-arrow-shape': 'triangle', width: 3 } },
  { selector: 'node[mismatch]', style: { 'border-width': 3, 'border-color': '#ff5252', 'background-color': '#8e3a3a' } },
]
